version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development 
    container_name: 'nest-container'
    environment:
      MONGO_URL: 'mongo'    
    ports:
      - 3000:3000
    depends_on:
      - mongo
    links: 
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    restart: always
    expose:
      - "27017"
    logging: 
      driver: none
volumes:
  mongo-data: {}